package models

import (
	"time"

	"github.com/google/uuid"
)

// WeeklyStatement is an immutable weekly settlement summary for a chef.
//
// Generated by the settlement cron once a Mon–Sun week (IST) closes. The
// totals are FROZEN at generation time so the chef always sees the same
// numbers on a given statement regardless of any later order mutation.
// The per-order line items shown in the PDF are re-derived from the
// (immutable, post-delivery) orders in the window — they always match.
//
// Uniqueness: one statement per (chef_id, week_start). The DB unique
// index is the hard guard against the cron double-issuing across pods;
// Redis SETNX is the soft guard that also suppresses the duplicate push.
type WeeklyStatement struct {
	ID     uuid.UUID `gorm:"type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	ChefID uuid.UUID `gorm:"type:uuid;not null;uniqueIndex:idx_weekly_stmt_chef_week" json:"chefId"`
	UserID uuid.UUID `gorm:"type:uuid;not null;index" json:"userId"`

	// Week boundaries. WeekStart is Monday 00:00 IST, WeekEnd is the
	// following Monday 00:00 IST (exclusive). Both stored in UTC.
	WeekStart time.Time `gorm:"not null;uniqueIndex:idx_weekly_stmt_chef_week" json:"weekStart"`
	WeekEnd   time.Time `gorm:"not null" json:"weekEnd"`

	Currency    string `gorm:"type:varchar(3);default:'INR'" json:"currency"`
	OrdersCount int    `gorm:"default:0" json:"ordersCount"`

	// Frozen totals (₹). Mirror services.EarningsTotals.
	GrossRevenue       float64 `gorm:"default:0" json:"grossRevenue"`
	PlatformCommission float64 `gorm:"default:0" json:"platformCommission"`
	CGST               float64 `gorm:"default:0" json:"cgst"`
	SGST               float64 `gorm:"default:0" json:"sgst"`
	IGST               float64 `gorm:"default:0" json:"igst"`
	TDS                float64 `gorm:"default:0" json:"tds"`
	NetPayout          float64 `gorm:"default:0" json:"netPayout"`

	// Payout disbursement tracking (admin). Statements are computed weekly by
	// the cron; disbursement is currently MANUAL (RazorpayX automation is
	// gated on an Indian entity — see payment-structuring decision). Admin
	// marks each statement paid after sending the transfer, recording the
	// gateway/bank reference.
	Status   PayoutStatus `gorm:"type:varchar(20);default:'pending';index" json:"status"`
	PaidAt   *time.Time   `gorm:"" json:"paidAt,omitempty"`
	PayoutRef string      `gorm:"" json:"payoutRef,omitempty"` // UTR / RazorpayX payout id / bank ref

	CreatedAt time.Time `gorm:"autoCreateTime" json:"createdAt"`
}

// PayoutStatus is the disbursement state of a weekly settlement statement.
type PayoutStatus string

const (
	PayoutPending PayoutStatus = "pending" // computed, not yet disbursed
	PayoutPaid    PayoutStatus = "paid"    // disbursed (manual or RazorpayX), PayoutRef set
)
